federation_version: =2.7.0
subgraphs:
  monolith:
    routing_url: http://localhost:4001
    schema:
      file: ../monolith/schema.graphql
  accounts:
    routing_url: http://localhost:4002
    schema:
      file: ../subgraph-accounts/schema.graphql
  payments:
    routing_url: http://localhost:4003
    schema:
      file: ../subgraph-payments/schema.graphql
  listings:
    routing_url: http://localhost:4004
    schema:
      file: ../subgraph-listings/schema.graphql
